34365: Github plugin feedback
tiobe/tics-github-action pull request #322
Opened 2024-06-04 14:51 UTC by wener-tiobe

2024-06-04 16:25 UTC, janssen-tiobe requested changes
Like the changes overall. Have two little change requests.

2024-06-04 16:25 UTC, janssen-tiobe commented on README.md
> +## Other features
I would remove `Mode(s)` from this table as it is always for all modes.

2024-06-04 16:25 UTC, janssen-tiobe commented on README.md
> +### Advanced parameters
I would add `nocalc` and `norecalc` in this table too, as it is used if set.

2024-06-05 08:03 UTC, zon-tiobe commented on README.md
> +| `secretsFilter`        | Comma-seperated list of extra secrets to mask in the console output.
Comma-seperated -> Comma-separated

2024-06-05 08:03 UTC, zon-tiobe commented on README.md
> +The interface (running with params) have been changed to depict their usage better or to synchronise with the TICS command line usage and by synchronous with other plugins we provide.
Sentence doesn't flow that nicely. I'd use something like this:

The interface (running with parameters) has been changed to better reflect its usage. This interface is now more synchronized with TICS command line usage, and have been changed to be closer to other plugins that TIOBE provides.

2024-06-05 08:03 UTC, zon-tiobe commented on README.md
> +There is also the possibility to do a so called "diagnostic" run. This mode can be enabled to test if TICS has been setup properly and can run on the machine the action is run on.
setup -> set up

2024-06-05 08:03 UTC, zon-tiobe commented on README.md
> +| `pullRequestApproval`  | Set the plugin to approve or deny a pull request, by default this is false. Options are `true` or `false`. Note that once a run that added a reviewer has been completed, th
Version of which tool? It helps to be certain about that :)

2024-06-05 08:03 UTC, zon-tiobe commented on README.md
> +| `codetype`             | Allows you to pick which specific types of code you want to analyze with the TICS client. Options are `PRODUCTION`, `TESTCODE` and `EXTERNAL`.         | `PRODUCTION`|
Technically, 'GENERATED' is also an option now. But that's probably the least interesting one.

2024-06-05 08:32 UTC, brouwers-tiobe commented on README.md
> +The TICS Github action integrates the [TICS code quality framework](https://www.tiobe.com/products/tics/) into your workflows. This allows you to effectively measure and monitor the software code qua
```suggestion
The TICS GitHub action integrates the [TICS code quality framework](https://www.tiobe.com/products/tics/) into your workflows. This allows you to effectively measure and monitor the software code quality of all your projects and their branches.

```

2024-06-05 08:32 UTC, brouwers-tiobe commented on README.md
> +- Reference runs using TICS QServer (See section QServer). Reference points with code quality metric data are created that are used for the qualification runs. Intended for branches where other branc
> Intended for branches where other branches are derived from and will be merged back to (Like main).

This reads a bit confusing to me. Perhaps we can incorporate the term 'base branch', which seems to be the conventional name in GitHub for 'the branch PRs are merged to'. For example: 'Intended for base branches of pull requests, e.g. `main`.' Similarly, we could refer to the 'branch to be merged' as 'head branch' of a PR

2024-06-05 08:32 UTC, brouwers-tiobe commented on README.md
> +Linux and Windows based runners, both Github-hosted and self-hosted, are supported.
```suggestion
Linux and Windows based runners, both GitHub-hosted and self-hosted, are supported.

```
(nitpick)

2024-06-05 08:32 UTC, brouwers-tiobe commented on README.md
> +| `calc`                 | Comma-separated list of [metrics](https://portal.tiobe.com/latest/docs/index.html#doc=user/clientoptions.html%23MetricAliases) to be used. The `GATE` metric is supported fo
```suggestion
| `calc`                 | Comma-separated list of [metrics](https://portal.tiobe.com/latest/docs/index.html#doc=user/clientoptions.html%23MetricAliases) to be calculated. The `GATE` metric is supported for TICS Viewer versions higher than 2022.2.x.              | `GATE`  |

```
(To keep in line with `nocalc`)

2024-06-05 08:32 UTC, brouwers-tiobe commented on README.md
> +Below are some special parameters that can be used to control how the Github Action posts its results:
```suggestion
Below are some special parameters that can be used to control how the GitHub Action posts its results:

```

2024-06-05 08:52 UTC, janssen-tiobe approved these changes

2024-06-05 09:01 UTC, zon-tiobe requested changes

2024-06-05 09:01 UTC, zon-tiobe commented on README.md
> +The interface (running with parameters) has been changed to better reflect its usage. This interface is now more synchronized with TICS command line usage, and have been changed to be closer to other
and have been changed -> and has been changed

2024-06-05 09:01 UTC, zon-tiobe commented on README.md
> +As of v3, the option to run [TICSQServer](https://ticsdocumentation.tiobe.com/latest/docs/#doc=admin/admin_A3_qserverref.html) analyses has been made available.
We are pointing to two different documentation links here:

https://portal.tiobe.com/latest/docs/index.html#doc=user/clientoptions.html%23MetricAliases
https://ticsdocumentation.tiobe.com/latest/docs/#doc=admin/admin_A3_qserverref.html

We should use one or the other in the entire README.

2024-06-05 10:27 UTC, zon-tiobe approved these changes
LGTM!

2024-06-06 10:41 UTC, merged